[package]
name = "targo"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
blake3 = "1.3.3"
camino = { version = "1.1.1", features = ["serde1"] }
cap-std = { version = "1.0.1", features = ["fs_utf8"] }
chrono = { version = "0.4.23", features = ["serde"] }
fs2 = "0.4.3"
toml = "0.5.9"
lexopt = { version = "0.2.1" }
color-eyre = { version = "0.6.2", default-features = false }
shell-words = { version = "1.1.0" }
semver = { version = "1.0.14", features = ["serde"] }
serde = { version = "1.0.148", features = ["derive"] }
serde_json = "1.0.89"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["fmt", "env-filter"] }
home = "0.5.4"
bs58 = "0.4.0"
clap = { version = "4.0.29", features = ["derive"] }

[dev-dependencies]
shell-words = "1.1.0"
